name: Generate Datas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Data for the Snake
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Data
        uses: Platane/snk@master
        with:
          github_user_name: Gabezz124
          svg_out_path: dist/github-contribution-grid-snake.svg
